=== AaronLunaa/ProjecteCarregarDades_JanCasanova_AaronLuna/ProjecteCarregarDades_JanCasanova_AaronLuna/cinema.dtd
<!DOCTYPE catalog [
  <!ELEMENT catalog (movie*)>
  <!ELEMENT movie (title, genre, director, year, rating, actors)>
  <!ATTLIST movie id CDATA #REQUIRED>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT genre (#PCDATA)>
  <!ELEMENT director (#PCDATA)>
  <!ELEMENT year (#PCDATA)>
  <!ELEMENT rating (#PCDATA)>
  <!ELEMENT actors (actor*)>
  <!ELEMENT actor EMPTY>
  <!ATTLIST actor name CDATA #REQUIRED>
  <!ATTLIST actor role CDATA #REQUIRED>
]>

=== AaronLunaa/ProjecteCarregarDades_JanCasanova_AaronLuna/cinema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "cinema.dtd">
<catalog>
  <movie id="1">
    <title>The Shawshank Redemption</title>
    <genre>Drama</genre>
    <director>Frank Darabont</director>
    <year>1994</year>
    <rating>9.3</rating>
    <actors>
      <actor name="Tim Robbins" role="Andy Dufresne" />
      <actor name="Morgan Freeman" role="Ellis Boyd 'Red' Redding" />
    </actors>
  </movie>
  <movie id="2">
    <title>The Godfather</title>
    <genre>Crime</genre>
    <director>Francis Ford Coppola</director>
    <year>1972</year>
    <rating>9.2</rating>
    <actors>
      <actor name="Marlon Brando" role="Don Vito Corleone" />
      <actor name="Al Pacino" role="Michael Corleone" />
    </actors>
  </movie>
  <movie id="3">
    <title>Pulp Fiction</title>
    <genre>Crime</genre>
    <director>Quentin Tarantino</director>
    <year>1994</year>
    <rating>8.9</rating>
    <actors>
      <actor name="John Travolta" role="Vincent Vega" />
      <actor name="Samuel L. Jackson" role="Jules Winnfield" />
    </actors>
  </movie>
  <movie id="4">
    <title>The Dark Knight</title>
    <genre>Action</genre>
    <director>Christopher Nolan</director>
    <year>2008</year>
    <rating>9.0</rating>
    <actors>
      <actor name="Christian Bale" role="Bruce Wayne / Batman" />
      <actor name="Heath Ledger" role="Joker" />
    </actors>
  </movie>
</catalog>
